version: '2'
services:
  db:
    image: mysql/mysql-server:latest #library/mysql:5.6.22
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=''

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/etengine
    ports:
      - "3000:3000"
    depends_on:
      - db
