version: '2'

volumes:
  mysql-data:
    driver: local
  rails-data:
    driver: local

services:
  db:
    image: mysql:5.7
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'etengine-dev-test'
      MYSQL_DATABASE: etengine_dev
    volumes:
      - mysql-data:/var/lib/mysql

  web:
    image: "etengine:latest"
    build:
      context: "."
      dockerfile: Dockerfile
    command: rails server -b 0.0.0.0 -p 3000 -P /tmp/rails.pid
    #working_dir: "/usr/src/app"
    volumes:
      - .:/etengine
      - rails-data:/usr/local/bundle
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    links:
    - db
    depends_on:
    - db
