class CreateBlockChartGqueries < ActiveRecord::Migration
  def self.up
    Gquery.create! :key => 'cost_chart_ccgt_cost', :query => 'future:PRODUCT(SUM(V(gas_ccgt_energy;total_cost_per_mwh_electricity)),1)'
    Gquery.create! :key => 'cost_chart_ccgt_investment', :query => 'future:PRODUCT(SUM(V(gas_ccgt_energy;initial_investment_costs_per_mw_electricity)),DIVIDE(1,MILLIONS))'
    Gquery.create! :key => 'cost_chart_gas_conv_cost', :query => 'future:PRODUCT(SUM(V(gas_conv_energy_energetic;total_cost_per_mwh_electricity)),1)'
    Gquery.create! :key => 'cost_chart_gas_conv_investment', :query => 'future:PRODUCT(SUM(V(gas_conv_energy_energetic;initial_investment_costs_per_mw_electricity)),DIVIDE(1,MILLIONS))'
    Gquery.create! :key => 'cost_chart_coal_cost', :query => 'future:PRODUCT(SUM(V(coal_pwd_energy;total_cost_per_mwh_electricity)),1)'
    Gquery.create! :key => 'cost_chart_coal_investment', :query => 'future:PRODUCT(SUM(V(coal_pwd_energy;initial_investment_costs_per_mw_electricity)),DIVIDE(1,MILLIONS))'
    Gquery.create! :key => 'cost_chart_co_f_coal_cost', :query => 'future:PRODUCT(SUM(V(co_firing_coal_energy;total_cost_per_mwh_electricity)),1)'
    Gquery.create! :key => 'cost_chart_co_f_coal_investment', :query => 'future:PRODUCT(SUM(V(co_firing_coal_energy;initial_investment_costs_per_mw_electricity)),DIVIDE(1,MILLIONS))'
    Gquery.create! :key => 'cost_chart_biomass_cost', :query => 'future:PRODUCT(SUM(V(biomass_chp_industry_energetic;total_cost_per_mwh_electricity)),1)'
    Gquery.create! :key => 'cost_chart_biomass_investment', :query => 'future:PRODUCT(SUM(V(biomass_chp_industry_energetic;initial_investment_costs_per_mw_electricity)),DIVIDE(1,MILLIONS))'
    Gquery.create! :key => 'cost_chart_coal_ccs_cost', :query => 'future:PRODUCT(SUM(V(coal_pwd_ccs_energy;total_cost_per_mwh_electricity)),1)'
    Gquery.create! :key => 'cost_chart_coal_ccs_investment', :query => 'future:PRODUCT(SUM(V(coal_pwd_ccs_energy;initial_investment_costs_per_mw_electricity)),DIVIDE(1,MILLIONS))'
    Gquery.create! :key => 'cost_chart_chp_large_cost', :query => 'future:PRODUCT(SUM(V(large_chp_industry_energetic;total_cost_per_mwh_electricity)),1)'
    Gquery.create! :key => 'cost_chart_chp_large_investment', :query => 'future:PRODUCT(SUM(V(large_chp_industry_energetic;initial_investment_costs_per_mw_electricity)),DIVIDE(1,MILLIONS))'
    Gquery.create! :key => 'cost_chart_chp_small_cost', :query => 'future:PRODUCT(SUM(V(chp_other_other_energetic;total_cost_per_mwh_electricity)),1)'
    Gquery.create! :key => 'cost_chart_chp_small_investment', :query => 'future:PRODUCT(SUM(V(chp_other_other_energetic;initial_investment_costs_per_mw_electricity)),DIVIDE(1,MILLIONS))'
    Gquery.create! :key => 'cost_chart_coal_chp_cost', :query => 'future:PRODUCT(SUM(V(coal_chp_energy;total_cost_per_mwh_electricity)),1)'
    Gquery.create! :key => 'cost_chart_coal_chp_investment', :query => 'future:PRODUCT(SUM(V(coal_chp_energy;initial_investment_costs_per_mw_electricity)),DIVIDE(1,MILLIONS))'
    Gquery.create! :key => 'cost_chart_oil_cost', :query => 'future:PRODUCT(SUM(V(oil_plant_energy;total_cost_per_mwh_electricity)),1)'
    Gquery.create! :key => 'cost_chart_oil_investment', :query => 'future:PRODUCT(SUM(V(oil_plant_energy;initial_investment_costs_per_mw_electricity)),DIVIDE(1,MILLIONS))'
    Gquery.create! :key => 'cost_chart_coal_conv_cost', :query => 'future:PRODUCT(SUM(V(coal_conv_energy;total_cost_per_mwh_electricity)),1)'
    Gquery.create! :key => 'cost_chart_coal_conv_investment', :query => 'future:PRODUCT(SUM(V(coal_conv_energy;initial_investment_costs_per_mw_electricity)),DIVIDE(1,MILLIONS))'
    Gquery.create! :key => 'cost_chart_igcc_ccs_cost', :query => 'future:PRODUCT(SUM(V(coal_igcc_ccs_energy;total_cost_per_mwh_electricity)),1)'
    Gquery.create! :key => 'cost_chart_igcc_ccs_investment', :query => 'future:PRODUCT(SUM(V(coal_igcc_ccs_energy;initial_investment_costs_per_mw_electricity)),DIVIDE(1,MILLIONS))'
    Gquery.create! :key => 'cost_chart_oxyfuel_cost', :query => 'future:PRODUCT(SUM(V(coal_oxyfuel_ccs_energy;total_cost_per_mwh_electricity)),1)'
    Gquery.create! :key => 'cost_chart_oxyfuel_investment', :query => 'future:PRODUCT(SUM(V(coal_oxyfuel_ccs_energy;initial_investment_costs_per_mw_electricity)),DIVIDE(1,MILLIONS))'
    Gquery.create! :key => 'cost_chart_lignite_cost', :query => 'future:PRODUCT(SUM(V(coal_lignite_energy;total_cost_per_mwh_electricity)),1)'
    Gquery.create! :key => 'cost_chart_lignite_investment', :query => 'future:PRODUCT(SUM(V(coal_lignite_energy;initial_investment_costs_per_mw_electricity)),DIVIDE(1,MILLIONS))'
    Gquery.create! :key => 'cost_chart_igcc_cost', :query => 'future:PRODUCT(SUM(V(coal_igcc_energy;total_cost_per_mwh_electricity)),1)'
    Gquery.create! :key => 'cost_chart_igcc_investment', :query => 'future:PRODUCT(SUM(V(coal_igcc_energy;initial_investment_costs_per_mw_electricity)),DIVIDE(1,MILLIONS))'
    Gquery.create! :key => 'cost_chart_inland_cost', :query => 'future:PRODUCT(SUM(V(wind_inland_energy;total_cost_per_mwh_electricity)),1)'
    Gquery.create! :key => 'cost_chart_inland_investment', :query => 'future:PRODUCT(SUM(V(wind_inland_energy;initial_investment_costs_per_mw_electricity)),DIVIDE(1,MILLIONS))'
    Gquery.create! :key => 'cost_chart_coastal_cost', :query => 'future:PRODUCT(SUM(V(wind_coastal_energy;total_cost_per_mwh_electricity)),1)'
    Gquery.create! :key => 'cost_chart_coastal_investment', :query => 'future:PRODUCT(SUM(V(wind_coastal_energy;initial_investment_costs_per_mw_electricity)),DIVIDE(1,MILLIONS))'
    Gquery.create! :key => 'cost_chart_offshore_cost', :query => 'future:PRODUCT(SUM(V(wind_offshore_energy;total_cost_per_mwh_electricity)),1)'
    Gquery.create! :key => 'cost_chart_offshore_investment', :query => 'future:PRODUCT(SUM(V(wind_offshore_energy;initial_investment_costs_per_mw_electricity)),DIVIDE(1,MILLIONS))'
    Gquery.create! :key => 'cost_chart_river_cost', :query => 'future:PRODUCT(SUM(V(hydro_river_energy;total_cost_per_mwh_electricity)),1)'
    Gquery.create! :key => 'cost_chart_river_investment', :query => 'future:PRODUCT(SUM(V(hydro_river_energy;initial_investment_costs_per_mw_electricity)),DIVIDE(1,MILLIONS))'
    Gquery.create! :key => 'cost_chart_geothermal_cost', :query => 'future:PRODUCT(SUM(V(geothermal_electricity_energy;total_cost_per_mwh_electricity)),1)'
    Gquery.create! :key => 'cost_chart_geothermal_investment', :query => 'future:PRODUCT(SUM(V(geothermal_electricity_energy;initial_investment_costs_per_mw_electricity)),DIVIDE(1,MILLIONS))'
    Gquery.create! :key => 'cost_chart_solar_pv_cost', :query => 'future:PRODUCT(SUM(V(local_solar_pv_grid_connected_energy_energetic;total_cost_per_mwh_electricity)),1)'
    Gquery.create! :key => 'cost_chart_solar_pv_investment', :query => 'future:PRODUCT(SUM(V(local_solar_pv_grid_connected_energy_energetic;initial_investment_costs_per_mw_electricity)),DIVIDE(1,MILLIONS))'
    Gquery.create! :key => 'cost_chart_solar_plant_cost', :query => 'future:PRODUCT(SUM(V(solar_pv_central_production_energy_energetic;total_cost_per_mwh_electricity)),1)'
    Gquery.create! :key => 'cost_chart_solar_plant_investment', :query => 'future:PRODUCT(SUM(V(solar_pv_central_production_energy_energetic;initial_investment_costs_per_mw_electricity)),DIVIDE(1,MILLIONS))'
    Gquery.create! :key => 'cost_chart_solar_csp_cost', :query => 'future:PRODUCT(SUM(V(solar_csp_energy;total_cost_per_mwh_electricity)),1)'
    Gquery.create! :key => 'cost_chart_solar_csp_investment', :query => 'future:PRODUCT(SUM(V(solar_csp_energy;initial_investment_costs_per_mw_electricity)),DIVIDE(1,MILLIONS))'
    Gquery.create! :key => 'cost_chart_nuclear_cost', :query => 'future:PRODUCT(SUM(V(nuclear_iii_energy;total_cost_per_mwh_electricity)),1)'
    Gquery.create! :key => 'cost_chart_nuclear_investment', :query => 'future:PRODUCT(SUM(V(nuclear_iii_energy;initial_investment_costs_per_mw_electricity)),DIVIDE(1,MILLIONS))'
    Gquery.create! :key => 'cost_chart_waste_cost', :query => 'future:PRODUCT(SUM(V(waste_incinerator_energy_energetic;total_cost_per_mwh_electricity)),1)'
    Gquery.create! :key => 'cost_chart_waste_investment', :query => 'future:PRODUCT(SUM(V(waste_incinerator_energy_energetic;initial_investment_costs_per_mw_electricity)),DIVIDE(1,MILLIONS))'
    Gquery.create! :key => 'cost_chart_mountain_cost', :query => 'future:PRODUCT(SUM(V(hydro_mount_energy;total_cost_per_mwh_electricity)),1)'
    Gquery.create! :key => 'cost_chart_mountain_investment', :query => 'future:PRODUCT(SUM(V(hydro_mount_energy;initial_investment_costs_per_mw_electricity)),DIVIDE(1,MILLIONS))'
    Gquery.create! :key => 'cost_chart_nuclear_conv_cost', :query => 'future:PRODUCT(SUM(V(nuclear_conv_energy_energetic;total_cost_per_mwh_electricity)),1)'
    Gquery.create! :key => 'cost_chart_nuclear_conv_investment', :query => 'future:PRODUCT(SUM(V(nuclear_conv_energy_energetic;initial_investment_costs_per_mw_electricity)),DIVIDE(1,MILLIONS))'
    Gquery.create! :key => 'cost_chart_ccgt_ccs_cost', :query => 'future:PRODUCT(SUM(V(ccgt_ccs_energy;total_cost_per_mwh_electricity)),1)'
    Gquery.create! :key => 'cost_chart_ccgt_ccs_investment', :query => 'future:PRODUCT(SUM(V(ccgt_ccs_energy;initial_investment_costs_per_mw_electricity)),DIVIDE(1,MILLIONS))'
  end

  def self.down
  end
end
